language: python
install:
  ./src/setup.sh
script:
  ./full-test.sh
before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y python3.7
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y opam
