apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proverbot9001-storage
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
